### ISSUE TITLE
Catch VC6 Sample Test compile errors

### ISSUE THREAD

**Issue by nagates** [martinmoene/Catch#23]
I'm trying to compile the basic setup example, and I get the following errors. 

testcatchsetup.cpp(9): error C2501: '__assertionInfo' : missing storage-class or type specifiers
\testcatchsetup.cpp(9): error C2143: syntax error : missing ';' before '('
\testcatchsetup.cpp(9): error C2064: term does not evaluate to a function
\testcatchsetup.cpp(9): error C2064: term does not evaluate to a function

Code 
# define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
# include "catch.hpp"

unsigned int Factorial( unsigned int number ) {
    return number <= 1 ? number : Factorial(number-1)*number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    REQUIRE( Factorial(1) == 1 );
//  REQUIRE( Factorial(2) == 2 );
//  REQUIRE( Factorial(3) == 6 );
//  REQUIRE( Factorial(10) == 3628800 );
}

**Comment by martinmoene** [comment]
Hi Nathaniel,

It would be helpful to know:
- which version of Catch-VC6 you used,
- which compiler you used,
- what command you used to compile the test program.

The code from the factorial sample program above works fine with Catch-VC6 v1.0 build 5 for me ;) both with the catch.hpp single include file and with the non-single include ('development') version.

I used:
- VC6: cl -nologo -W3 -EHsc -I../../../include test-factorial.cpp && test-factorial.exe
- VC6: cl -nologo -W3 -EHsc -I../../../single_include test-factorial.cpp && test-factorial.exe
- g++ 4.8.1: g++ -Wall -I../../../include -o test-factorial.exe test-factorial.cpp && test-factorial.exe

Martin
